# Generated by Django 4.2.16 on 2025-05-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficio', '0002_beneficio_delete_tipobeneficio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField(max_length=20000, verbose_name='Texto *')),
                ('arquivo_notificao', models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo do texto do despacho *')),
                ('envios_email', models.IntegerField(default=0, verbose_name='Quantidade de vezes que o despacho foi notificado por email.')),
                ('data_ultimo_envio', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o despacho pode ser usado no sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficio', to='beneficio.beneficio', verbose_name='Beneficio associado *')),
            ],
            options={
                'verbose_name': 'despacho',
                'verbose_name_plural': 'despachos',
                'ordering': ['-is_active', 'data_criacao', 'beneficio'],
            },
        ),
    ]
