# Generated by Django 4.2.16 on 2025-06-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='despachos/'),
        ),
    ]
