# Generated by Django 4.2.16 on 2025-05-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBeneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, help_text='* Campo obrigatório', max_length=100, unique=True, verbose_name='Título do beneficio *')),
                ('descricao', models.CharField(help_text='* Campo obrigatório', max_length=500, verbose_name='Descrição do beneficio *')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o tipo de benefício pode ser usado no sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'tipos',
                'ordering': ['-is_active', 'titulo'],
            },
        ),
    ]
