# Generated by Django 4.2.16 on 2025-05-12 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_beneficio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beneficio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_beneficio', models.CharField(db_index=True, help_text='* Campo obrigatório', max_length=100, unique=True, verbose_name='Número do beneficio *')),
                ('nome_beneficiario', models.CharField(max_length=100, verbose_name='Nome completo *')),
                ('cpf', models.CharField(help_text='ATENÇÃO: Somente os NÚMEROS', max_length=14, verbose_name='CPF *')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email')),
                ('estado', models.CharField(max_length=30, verbose_name='Estado ou província *')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('rua', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua')),
                ('numero_residencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número')),
                ('complemento_residencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o tipo de benefício pode ser usado no sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficios', to=settings.AUTH_USER_MODEL, verbose_name='Servidor delegado *')),
                ('tipo_beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficios', to='tipo_beneficio.tipobeneficio', verbose_name='Tipo de Benefício *')),
            ],
            options={
                'verbose_name': 'numero_beneficio',
                'verbose_name_plural': 'numero_beneficio',
                'ordering': ['-is_active', 'numero_beneficio'],
            },
        ),
        migrations.DeleteModel(
            name='TipoBeneficio',
        ),
    ]
