# Generated by Django 4.2.16 on 2025-05-02 18:27

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import usuario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicao', '0002_alter_instituicao_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tipo', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('COORDENADOR', 'Coordenador'), ('MEMBRO', 'Membro')], help_text='* Campos obrigatórios', max_length=15, verbose_name='Tipo do usuário *')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo *')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email')),
                ('cpf', models.CharField(help_text='ATENÇÃO: Somente os NÚMEROS', max_length=14, verbose_name='CPF *')),
                ('is_active', models.BooleanField(default=False, help_text='Se ativo, o usuário tem permissão para acessar o sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituicao', to='instituicao.instituicao', verbose_name='APS vinculado *')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['-tipo', 'nome'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('administradores', usuario.models.AdministradorAtivoManager()),
                ('coordenadores', usuario.models.CoordenadorAtivoManager()),
                ('membros', usuario.models.MembroAtivoManager()),
                ('usuarios_ativos', usuario.models.UsuarioAtivoManager()),
            ],
        ),
    ]
