# Generated by Django 4.2.16 on 2025-05-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='instituicao',
        ),
    ]
