# Generated by Django 4.2.16 on 2025-05-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0002_alter_instituicao_cidade'),
        ('usuario', '0003_usuario_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='instituicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instituicao', to='instituicao.instituicao', verbose_name='APS vinculado *'),
        ),
    ]
